# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies
install: pip install -U tox-travis codecov

after_success: codecov

# Command to run tests
script:
  - tox
  - make docs

deploy:

  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6
